// src/types/eventsList.ts

export interface CampusEvent {
  id: number;
  title: string;
  date: string;
  startTime: string;
  endTime: string | null;
  location: string;
  category: string;
  locationId: string | null; // maps to CampusLocation.id in locations.ts (on-campus)
  address: string | null;    // full address string for off-campus venues
}

export const campusEvents: CampusEvent[] = [
  // ── Wednesday, April 1 ──
  {
    id: 1,
    title: "Welcome Back Bowling Party (JL Moran Chapter)",
    date: "Wednesday, April 1",
    startTime: "12:00 PM",
    endTime: "4:00 PM",
    location: "Stars & Strikes",
    category: "Social",
    locationId: null,
    address: "Stars & Strikes, Huntsville, AL",
  },
  {
    id: 2,
    title: "Writers Gather",
    date: "Wednesday, April 1",
    startTime: "4:00 PM",
    endTime: "5:30 PM",
    location: "McKee (B&T) Building",
    category: "Workshop",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 3,
    title: "Mind Your Own Business",
    date: "Wednesday, April 1",
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    location: "McKee (B&T) Building",
    category: "Workshop",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 4,
    title: "OU On the Yard",
    date: "Sunday, April 19",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "The Quad (between Wade & Cooper Complex)",
    category: "Social",
    locationId: "jesus_statue",
    address: null,
  },
  {
    id: 5,
    title: "OU Central Park",
    date: "Wednesday, April 1",
    startTime: "12:00 PM",
    endTime: null,
    location: "In front of Blake Center",
    category: "Social",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 35,
    title: "Mr. Frank Williams Panel Discussion (Alumni 360)",
    date: "Wednesday, April 1",
    startTime: "5:00 PM",
    endTime: null,
    location: "McKee Business & Technology Complex Auditorium",
    category: "Meeting",
    locationId: "mckee_bt",
    address: null,
  },

  // ── Thursday, April 2 ──
  {
    id: 6,
    title: "Alumni Business Meeting",
    date: "Thursday, April 2",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    location: "McKee (B&T) Building",
    category: "Meeting",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 7,
    title: "Alumni Basketball Tournament",
    date: "Thursday, April 2",
    startTime: "12:00 PM",
    endTime: "11:30 PM",
    location: "Ashby Gymnasium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 8,
    title: "OU Central Park",
    date: "Thursday, April 2",
    startTime: "12:00 PM",
    endTime: null,
    location: "In front of Blake Center",
    category: "Social",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 9,
    title: "Gold & Blue Gala",
    date: "Thursday, April 2",
    startTime: "6:00 PM",
    endTime: "9:00 PM",
    location: "Jackson Center",
    category: "Ceremony",
    locationId: null,
    address: "Jackson Center, Huntsville, AL",
  },
  {
    id: 36,
    title: "Smart Design School (Alumni 360)",
    date: "Thursday, April 2",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    location: "McKee Business & Technology Building",
    category: "Workshop",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 37,
    title: "The Real Med Talk (Alumni 360)",
    date: "Thursday, April 2",
    startTime: "2:30 PM",
    endTime: "3:45 PM",
    location: "Cooper Complex Auditorium",
    category: "Meeting",
    locationId: "cooper_cc2",
    address: null,
  },
  {
    id: 38,
    title: "Dr. Emerson Cooper Lecture Series (Alumni 360)",
    date: "Thursday, April 2",
    startTime: "5:00 PM",
    endTime: "6:15 PM",
    location: "Business & Technology Building Auditorium",
    category: "Meeting",
    locationId: "mckee_bt",
    address: null,
  },

  // ── Friday, April 3 ──
  {
    id: 10,
    title: "Alumni Basketball Tournament",
    date: "Friday, April 3",
    startTime: "8:00 AM",
    endTime: "4:00 PM",
    location: "Ashby Gymnasium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 11,
    title: "Music Legacy Awards",
    date: "Friday, April 3",
    startTime: "11:00 AM",
    endTime: "12:30 PM",
    location: "Peters Recital Hall",
    category: "Music",
    locationId: "peters_hall",
    address: null,
  },
  {
    id: 12,
    title: "Rook Tournament (OOAA Event)",
    date: "Friday, April 3",
    startTime: "11:00 AM",
    endTime: null,
    location: "Embassy Suites Hotel",
    category: "Sports",
    locationId: null,
    address: "Embassy Suites by Hilton Huntsville Hotel & Spa, Huntsville, AL",
  },
  {
    id: 13,
    title: "OU Central Park",
    date: "Friday, April 3",
    startTime: "12:00 PM",
    endTime: null,
    location: "In front of Blake Center",
    category: "Social",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 14,
    title: "Prayer at Bell Tower",
    date: "Friday, April 3",
    startTime: "12:30 PM",
    endTime: "1:00 PM",
    location: "Bell Tower",
    category: "Spiritual",
    locationId: "bell_tower",
    address: null,
  },
  {
    id: 15,
    title: "Oak Tree Memorial Dedication",
    date: "Friday, April 3",
    startTime: "1:00 PM",
    endTime: "1:30 PM",
    location: "Blue & Gold Ribboned Tree",
    category: "Ceremony",
    locationId: "bell_tower",
    address: null,
  },
  {
    id: 16,
    title: "Finance Town Hall Meeting",
    date: "Friday, April 3",
    startTime: "1:00 PM",
    endTime: "2:00 PM",
    location: "Peters Music Building",
    category: "Meeting",
    locationId: "peters_hall",
    address: null,
  },
  {
    id: 17,
    title: "Vespers",
    date: "Friday, April 3",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: null,
  },
  {
    id: 18,
    title: "Concert",
    date: "Friday, April 3",
    startTime: "7:15 PM",
    endTime: "9:30 PM",
    location: "Oakwood University Church",
    category: "Music",
    locationId: "oakwood_church",
    address: null,
  },
  {
    id: 39,
    title: "Education Department Alumni Brunch (Alumni 360)",
    date: "Friday, April 3",
    startTime: "10:00 AM",
    endTime: null,
    location: "Anna Knight Hall",
    category: "Social",
    locationId: "knight_hall",
    address: null,
  },
  {
    id: 40,
    title: "Rhyne/Duncan Biomedical Symposium (Alumni 360)",
    date: "Friday, April 3",
    startTime: "10:00 AM",
    endTime: "12:30 PM",
    location: "Cooper Complex Auditorium",
    category: "Meeting",
    locationId: "cooper_cc1",
    address: null,
  },
  {
    id: 41,
    title: "Mock Trial & Attorney Alumni Chapter Launch (Alumni 360)",
    date: "Friday, April 3",
    startTime: "10:00 AM",
    endTime: null,
    location: "Huntsville Municipal Court",
    category: "Meeting",
    locationId: null,
    address: "Huntsville Municipal Court, 815 Wheeler Ave NW, Huntsville, AL 35801",
  },
  {
    id: 42,
    title: "Smart Design School (Alumni 360)",
    date: "Friday, April 3",
    startTime: "11:00 AM",
    endTime: "1:00 PM",
    location: "McKee Business & Technology Building",
    category: "Workshop",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 43,
    title: "2026 Music Legacy Awards (Alumni 360)",
    date: "Friday, April 3",
    startTime: "11:00 AM",
    endTime: null,
    location: "Peters Music Hall",
    category: "Music",
    locationId: "peters_hall",
    address: null,
  },

  // ── Saturday, April 4 ──
  {
    id: 19,
    title: "Sabbath School",
    date: "Saturday, April 4",
    startTime: "9:00 AM",
    endTime: "10:30 AM",
    location: "Von Braun Center",
    category: "Spiritual",
    locationId: null,
    address: "Von Braun Center, Huntsville, AL",
  },
  {
    id: 20,
    title: "Divine Service",
    date: "Saturday, April 4",
    startTime: "10:45 AM",
    endTime: "1:00 PM",
    location: "Von Braun Center",
    category: "Spiritual",
    locationId: null,
    address: "Von Braun Center, Huntsville, AL",
  },
  {
    id: 21,
    title: "Next Gen. Oakwood Worship Service",
    date: "Saturday, April 4",
    startTime: "10:45 AM",
    endTime: "1:00 PM",
    location: "VBC Concert Hall",
    category: "Spiritual",
    locationId: null,
    address: "Von Braun Center Concert Hall, Huntsville, AL",
  },
  {
    id: 22,
    title: "Fellowship Luncheon",
    date: "Saturday, April 4",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "OUC (Family Life Center)",
    category: "Social",
    locationId: "family_life_center",
    address: null,
  },
  {
    id: 23,
    title: "BAMDA Sabbath Luncheon (OOAA Event)",
    date: "Saturday, April 4",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "Von Braun Center",
    category: "Social",
    locationId: null,
    address: "Von Braun Center, Huntsville, AL",
  },
  {
    id: 24,
    title: "Aeolians Concert",
    date: "Saturday, April 4",
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    location: "Oakwood University Church",
    category: "Music",
    locationId: "oakwood_church",
    address: null,
  },
  {
    id: 25,
    title: "Student Performing Arts Showcase",
    date: "Saturday, April 4",
    startTime: "8:30 PM",
    endTime: null,
    location: "Millet Activity Center (MAC)",
    category: "Music",
    locationId: "mac",
    address: null,
  },
  {
    id: 26,
    title: "Laugh & Groove Comedy Show",
    date: "Saturday, April 4",
    startTime: "8:30 PM",
    endTime: null,
    location: "McKee B&T Auditorium",
    category: "Social",
    locationId: "mckee_bt",
    address: null,
  },
  {
    id: 27,
    title: "Alumni Basketball Tournament",
    date: "Saturday, April 4",
    startTime: "8:00 PM",
    endTime: "12:00 AM",
    location: "Ashby Gymnasium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 28,
    title: "Dominoes Tournament & Old-Fashioned Social (OOAA Event)",
    date: "Saturday, April 4",
    startTime: "9:00 PM",
    endTime: "11:00 PM",
    location: "Embassy Suites Hotel",
    category: "Social",
    locationId: null,
    address: "Embassy Suites by Hilton Huntsville Hotel & Spa, Huntsville, AL",
  },

  // ── Sunday, April 5 ──
  {
    id: 29,
    title: "Alumni 5K Fundraiser",
    date: "Sunday, April 5",
    startTime: "8:00 AM",
    endTime: "11:00 AM",
    location: "Campus Route",
    category: "Sports",
    locationId: "track_field",
    address: null,
  },
  {
    id: 30,
    title: "Vendor Village",
    date: "Sunday, April 5",
    startTime: "9:00 AM",
    endTime: "2:00 PM",
    location: "The Quad (between Wade & Cooper Complex)",
    category: "Social",
    locationId: "jesus_statue",
    address: null,
  },
  {
    id: 31,
    title: "Alumni Basketball Tournament",
    date: "Sunday, April 5",
    startTime: "9:00 AM",
    endTime: "4:00 PM",
    location: "Ashby Gymnasium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 32,
    title: "The Resurrection Experience – The Road to Calvary",
    date: "Sunday, April 5",
    startTime: "10:00 AM",
    endTime: null,
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: null,
  },
  {
    id: 33,
    title: "MACS Alumni Fundraiser Brunch",
    date: "Sunday, April 5",
    startTime: "10:00 AM",
    endTime: "1:00 PM",
    location: "CC2 Cooper Complex (Middle Building Upstairs)",
    category: "Social",
    locationId: "cooper_cc2",
    address: null,
  },
  {
    id: 34,
    title: "2016 Championship Team vs. OU Men's Basketball",
    date: "Sunday, April 5",
    startTime: "3:00 PM",
    endTime: "5:30 PM",
    location: "The Quad (between Wade & Cooper Complex)",
    category: "Sports",
    locationId: "jesus_statue",
    address: null,
  },
  {
    id: 44,
    title: "School of Business Alumni 360 Brunch",
    date: "Sunday, April 5",
    startTime: "10:00 AM",
    endTime: "12:00 PM",
    location: "TBD",
    category: "Social",
    locationId: null,
    address: "Oakwood University, Huntsville, AL",
  },
  {
    id: 45,
    title: "Alumni Social Work Brunch (Alumni 360)",
    date: "Sunday, April 5",
    startTime: "11:00 AM",
    endTime: null,
    location: "Bradford Cleveland-Brooks Leadership Center",
    category: "Social",
    locationId: "bradford_cleveland",
    address: null,
  },
  {
  id: 46,
  title: "Alumni vs. Students Soccer Game",
  date: "Sunday, April 5",
  startTime: "2:30 PM",
  endTime: "4:00 PM",
  location: "Soccer Field",
  category: "Sports",
  locationId: "soccer_field",
  address: null,
},
];