// src/types/eventsList.ts

export interface CampusEvent {
  id: number;
  title: string;
  date: string;
  startTime: string;
  endTime: string | null;
  location: string;
  category: string;
  locationId: string | null;
  address: string | null;
}

export const campusEvents: CampusEvent[] = [

  // ── Wednesday, September 30, 2026 ──
  {
    id: 1,
    title: "Registration Check-In & Light Refreshments — Residence Hall Check-In",
    date: "Wednesday, September 30",
    startTime: "8:00 AM",
    endTime: "7:00 PM",
    location: "Bradford Cleveland Brooks Leadership Center — Lobby and Banquet Room",
    category: "Meeting",
    locationId: "bradford_cleveland",
    address: null,
  },
  {
    id: 2,
    title: "Campus Tours — A View of the Oaks",
    date: "Wednesday, September 30",
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Meet at Dining Tent at Blake Center",
    category: "Social",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 3,
    title: "Residence Halls Tours — Where the New Students Reside",
    date: "Wednesday, September 30",
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Carter, Holland, and Peterson — Start Blake Center Dining Tent",
    category: "Social",
    locationId: "carter_hall",
    address: null,
  },
  {
    id: 4,
    title: "Enrollment Process Help-Station",
    date: "Wednesday, September 30",
    startTime: "10:00 AM",
    endTime: "3:00 PM",
    location: "Cunningham Hall, 2nd Floor Conference Room",
    category: "Academic",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 5,
    title: "Lunch (All Attendees)",
    date: "Wednesday, September 30",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 6,
    title: "Biological and Biomedical Research Symposium — All May Attend",
    date: "Wednesday, September 30",
    startTime: "2:30 PM",
    endTime: "3:15 PM",
    location: "Cooper Complex 1 — Lower Level (Biology Department)",
    category: "Academic",
    locationId: "cooper_cc1",
    address: null,
  },
  {
    id: 7,
    title: "OU Live 2026 Kick-Off Procession to Church",
    date: "Wednesday, September 30",
    startTime: "3:00 PM",
    endTime: "3:30 PM",
    location: "Campus Quad — between Blake Center, Carter Hall, and Peters Hall",
    category: "Spiritual",
    locationId: "ou_central_park",
    address: null,
  },
  {
    id: 8,
    title: "Welcome and OU Live 2026 Kick-Off",
    date: "Wednesday, September 30",
    startTime: "3:30 PM",
    endTime: "4:45 PM",
    location: "Oakwood University Church Sanctuary",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Dr NW, Huntsville, AL",
  },
  {
    id: 9,
    title: "Supper (Student Attendees)",
    date: "Wednesday, September 30",
    startTime: "5:00 PM",
    endTime: "6:45 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 10,
    title: "Chaperones Only — OU Live Orientation & Supper",
    date: "Wednesday, September 30",
    startTime: "5:15 PM",
    endTime: "6:45 PM",
    location: "Office for Regional Conference Ministries",
    category: "Meeting",
    locationId: null,
    address: "5100 Adventist Blvd NW, Huntsville, AL",
  },
  {
    id: 11,
    title: "Softball Vs. Baseball Game",
    date: "Wednesday, September 30",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
    location: "Softball Field behind Ashby Auditorium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 12,
    title: "Prayer Meeting — Speaker: Je'Chaun Pottinger",
    date: "Wednesday, September 30",
    startTime: "7:00 PM",
    endTime: "8:30 PM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Blvd, Huntsville, AL 35896",
  },
  {
    id: 13,
    title: "Mr. & Ms. OU Live Talent Showcase",
    date: "Wednesday, September 30",
    startTime: "8:30 PM",
    endTime: "10:30 PM",
    location: "Millet Activity Center (MAC)",
    category: "Social",
    locationId: "mac",
    address: null,
  },
  {
    id: 14,
    title: "Return to Residence Halls",
    date: "Wednesday, September 30",
    startTime: "10:30 PM",
    endTime: null,
    location: "Residence Halls",
    category: "Social",
    locationId: "carter_hall",
    address: null,
  },

  // ── Thursday, October 1, 2026 ──
  {
    id: 15,
    title: "Breakfast",
    date: "Thursday, October 1",
    startTime: "7:20 AM",
    endTime: "9:00 AM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 16,
    title: "Registration Check-In — Residence Hall Check-In",
    date: "Thursday, October 1",
    startTime: "8:00 AM",
    endTime: "5:00 PM",
    location: "Cunningham Hall 2nd Floor Main Lobby",
    category: "Meeting",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 17,
    title: "Chapel — Speaker: Pr. John T. Boston II",
    date: "Thursday, October 1",
    startTime: "9:50 AM",
    endTime: "11:15 AM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Dr NW, Huntsville, AL 35896",
  },
  {
    id: 18,
    title: "Lunch (All Attendees)",
    date: "Thursday, October 1",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 19,
    title: "Women's Volleyball Tryouts",
    date: "Thursday, October 1",
    startTime: "12:00 PM",
    endTime: "1:00 PM",
    location: "Ashby Gymnasium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 20,
    title: "Pathways Preview — Academic School Open House",
    date: "Thursday, October 1",
    startTime: "1:00 PM",
    endTime: "2:15 PM",
    location: "Multiple Locations — Arts & Sciences: Peters Hall, Business: McKee B&T, Health/Education: Mosley Complex, Religion: Mosley Complex Lobby, Grad Studies: Cunningham Hall",
    category: "Academic",
    locationId: "peters_hall",
    address: null,
  },
  {
    id: 21,
    title: "Academic Department Showcase",
    date: "Thursday, October 1",
    startTime: "2:30 PM",
    endTime: "3:45 PM",
    location: "Reference Sign-Up — Download Expo Pass Mobile App",
    category: "Academic",
    locationId: null,
    address: "Oakwood University, Huntsville, AL",
  },
  {
    id: 22,
    title: "Enrollment Process Help-Station",
    date: "Thursday, October 1",
    startTime: "2:30 PM",
    endTime: "3:45 PM",
    location: "Cunningham Hall, 2nd Floor Conference Room 227",
    category: "Academic",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 23,
    title: "Student Financial Aid Workshops — Where the Money Resides",
    date: "Thursday, October 1",
    startTime: "2:30 PM",
    endTime: "3:45 PM",
    location: "Cunningham Hall, Rooms 223 & 234",
    category: "Academic",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 24,
    title: "Residence Hall Tours — Where the New Students Reside",
    date: "Thursday, October 1",
    startTime: "2:30 PM",
    endTime: "3:45 PM",
    location: "Carter, Holland, and Peterson — Start Blake Center Dining Tent",
    category: "Social",
    locationId: "carter_hall",
    address: null,
  },
  {
    id: 25,
    title: "Academic Department Showcase",
    date: "Thursday, October 1",
    startTime: "4:00 PM",
    endTime: "5:15 PM",
    location: "Reference Sign-Up — Download Expo Pass Mobile App",
    category: "Academic",
    locationId: null,
    address: "Oakwood University, Huntsville, AL",
  },
  {
    id: 26,
    title: "Enrollment Process Help-Station",
    date: "Thursday, October 1",
    startTime: "4:00 PM",
    endTime: "5:15 PM",
    location: "Cunningham Hall, 2nd Floor Conference Room",
    category: "Academic",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 27,
    title: "Student Financial Aid Workshops — Where the Money Resides",
    date: "Thursday, October 1",
    startTime: "4:00 PM",
    endTime: "5:15 PM",
    location: "Cunningham Hall, Room 223 & 234",
    category: "Academic",
    locationId: "cunningham_hall",
    address: null,
  },
  {
    id: 28,
    title: "Residence Hall Tours — Where the New Students Reside",
    date: "Thursday, October 1",
    startTime: "4:00 PM",
    endTime: "5:15 PM",
    location: "Carter, Holland, and Peterson — Start Blake Center Dining Tent",
    category: "Social",
    locationId: "carter_hall",
    address: null,
  },
  {
    id: 29,
    title: "Supper",
    date: "Thursday, October 1",
    startTime: "5:15 PM",
    endTime: "7:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 30,
    title: "Oakwood Live — Mass Choir Rehearsal",
    date: "Thursday, October 1",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
    location: "Mosley Complex Chapel",
    category: "Music",
    locationId: "mosley_complex",
    address: null,
  },
  {
    id: 31,
    title: "Creative Worship Experience",
    date: "Thursday, October 1",
    startTime: "7:45 PM",
    endTime: "10:00 PM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Dr NW, Huntsville, AL 35896",
  },

  // ── Friday, October 2, 2026 ──
  {
    id: 32,
    title: "Breakfast",
    date: "Friday, October 2",
    startTime: "7:30 AM",
    endTime: "9:00 AM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 33,
    title: "Registration Check-In & Residence Hall Check-In",
    date: "Friday, October 2",
    startTime: "8:30 AM",
    endTime: "12:00 PM",
    location: "Millet Activity Center (MAC)",
    category: "Meeting",
    locationId: "mac",
    address: null,
  },
  {
    id: 34,
    title: "Academic Fair and Support Services Showcase",
    date: "Friday, October 2",
    startTime: "8:30 AM",
    endTime: "12:00 PM",
    location: "Millet Activity Center (MAC)",
    category: "Academic",
    locationId: "mac",
    address: null,
  },
  {
    id: 35,
    title: "Acceptance Decision Release Celebration",
    date: "Friday, October 2",
    startTime: "10:00 AM",
    endTime: "11:30 AM",
    location: "Millet Activity Center (MAC)",
    category: "Social",
    locationId: "mac",
    address: null,
  },
  {
    id: 36,
    title: "Lunch",
    date: "Friday, October 2",
    startTime: "11:30 AM",
    endTime: "1:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 37,
    title: "Aeolians Rehearsals",
    date: "Friday, October 2",
    startTime: "12:00 AM",
    endTime: "1:00 PM",
    location: "Peters Music Hall — Auditorium",
    category: "Music",
    locationId: "peters_hall",
    address: null,
  },
  {
    id: 38,
    title: "Curating My College Experience — Speakers Mr. & Ms. Oakwood",
    date: "Friday, October 2",
    startTime: "1:00 PM",
    endTime: "2:00 PM",
    location: "Cooper Complex II, Room 420",
    category: "Academic",
    locationId: "cooper_cc2",
    address: null,
  },
  {
    id: 39,
    title: "Volleyball Scrimmage Game",
    date: "Friday, October 2",
    startTime: "1:00 PM",
    endTime: "2:00 PM",
    location: "Ashby Auditorium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 40,
    title: "Back to the Playground: Business Edition",
    date: "Friday, October 2",
    startTime: "1:00 PM",
    endTime: "3:00 PM",
    location: "Soccer Field near Cooper Complex",
    category: "Social",
    locationId: "soccer_field",
    address: null,
  },
  {
    id: 41,
    title: "Free Time",
    date: "Friday, October 2",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "Campus",
    category: "Social",
    locationId: null,
    address: "Oakwood University, Huntsville, AL",
  },
  {
    id: 42,
    title: "One Act Stage Play — ACTS (Actors Called to Serve)",
    date: "Friday, October 2",
    startTime: "2:00 PM",
    endTime: "3:00 PM",
    location: "Moran Hall Auditorium",
    category: "Social",
    locationId: "moran_hall",
    address: null,
  },
  {
    id: 43,
    title: "Men's Basketball Tryouts",
    date: "Friday, October 2",
    startTime: "2:30 PM",
    endTime: "3:30 PM",
    location: "Ashby Auditorium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 44,
    title: "Curating My College Experience — Speakers Mr. & Ms. Oakwood",
    date: "Friday, October 2",
    startTime: "3:00 PM",
    endTime: "4:00 PM",
    location: "Cooper Complex II, Room 420",
    category: "Academic",
    locationId: "cooper_cc2",
    address: null,
  },
  {
    id: 45,
    title: "Women's Basketball Tryouts",
    date: "Friday, October 2",
    startTime: "3:30 PM",
    endTime: "4:30 PM",
    location: "Ashby Auditorium",
    category: "Sports",
    locationId: "ashby_gymnasium",
    address: null,
  },
  {
    id: 46,
    title: "Supper",
    date: "Friday, October 2",
    startTime: "4:00 PM",
    endTime: "5:30 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 47,
    title: "Dynamic Praise Choir Rehearsal",
    date: "Friday, October 2",
    startTime: "4:30 PM",
    endTime: "6:00 PM",
    location: "Moran Hall Auditorium",
    category: "Music",
    locationId: "moran_hall",
    address: null,
  },
  {
    id: 48,
    title: "Voices of Triumph Choir Rehearsal",
    date: "Friday, October 2",
    startTime: "5:00 PM",
    endTime: "6:30 PM",
    location: "Peterson Hall Chapel",
    category: "Music",
    locationId: "peterson_hall",
    address: null,
  },
  {
    id: 49,
    title: "Oakwood Live — Mass Choir Rehearsal",
    date: "Friday, October 2",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
    location: "Oakwood University Church, Multipurpose Rooms 1 & 2",
    category: "Music",
    locationId: "oakwood_church",
    address: null,
  },
  {
    id: 50,
    title: "AYM Release — OU Live 2026 Edition",
    date: "Friday, October 2",
    startTime: "7:30 PM",
    endTime: "10:00 PM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Dr, NW, Huntsville, AL",
  },

  // ── Saturday, October 3, 2026 ──
  {
    id: 51,
    title: "Breakfast",
    date: "Saturday, October 3",
    startTime: "9:00 AM",
    endTime: "10:00 AM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 52,
    title: "Worship Service",
    date: "Saturday, October 3",
    startTime: "11:00 AM",
    endTime: "1:30 PM",
    location: "Oakwood University Church",
    category: "Spiritual",
    locationId: "oakwood_church",
    address: "5500 Adventist Dr NW, Huntsville, AL 35896",
  },
  {
    id: 53,
    title: "Lunch",
    date: "Saturday, October 3",
    startTime: "2:00 PM",
    endTime: "4:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 54,
    title: "Service Project — OU Live Food Drive",
    date: "Saturday, October 3",
    startTime: "3:30 PM",
    endTime: "5:00 PM",
    location: "Oakwood University Church Family Life Center — OU Pantry",
    category: "Social",
    locationId: "family_life_center",
    address: null,
  },
  {
    id: 55,
    title: "Supper (Grab & Go Sack-Meal)",
    date: "Saturday, October 3",
    startTime: "5:00 PM",
    endTime: "6:00 PM",
    location: "Blake Center Dining Hall",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 56,
    title: "Travel to James Clemens High School Gymnasium",
    date: "Saturday, October 3",
    startTime: "6:00 PM",
    endTime: "7:00 PM",
    location: "Meet at Blake Center Parking Lot",
    category: "Social",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 57,
    title: "Women's and Men's Basketball Games",
    date: "Saturday, October 3",
    startTime: "7:00 PM",
    endTime: "11:00 PM",
    location: "James Clemens High School Gymnasium",
    category: "Sports",
    locationId: null,
    address: "James Clemens High School, Madison, AL",
  },

  // ── Sunday, October 4, 2026 ──
  {
    id: 58,
    title: "Breakfast Available for Purchase",
    date: "Sunday, October 4",
    startTime: "6:30 AM",
    endTime: "8:30 AM",
    location: "Dining Tent at Blake Center",
    category: "Dining",
    locationId: "blake_center",
    address: null,
  },
  {
    id: 59,
    title: "Check Out / Departure",
    date: "Sunday, October 4",
    startTime: "10:00 AM",
    endTime: null,
    location: "Residence Halls",
    category: "Meeting",
    locationId: "carter_hall",
    address: null,
  },
];